name: Build Tailwind CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies and set permissions
        run: |
          npm install
          chmod +x ./node_modules/.bin/tailwindcss

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./src/styles.css -o ./src/output.css

      - name: Commit and push output.css
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add src/output.css
          git commit -m 'Build Tailwind output.css' || echo "No changes to commit"
          git push
